name: GenSym CI Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Repository Structure
        run: ls -R  # Debugging step to check if CMakeLists.txt exists

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang llvm cmake make python3 z3 libz3-dev

      - name: Verify CMakeLists.txt Location
        run: |
          find . -name "CMakeLists.txt"

      - name: Build GenSym
        run: |
          if [ -f CMakeLists.txt ]; then
            mkdir -p build
            cd build
            cmake ..
            make -j$(nproc)
          else
            echo "Error: CMakeLists.txt not found!"
            exit 1
          fi

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure
