name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04  # Force Ubuntu 20.04 for LLVM compatibility
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        llvm-version: [11, 14]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up LLVM and Clang
      run: |
        sudo apt-get update && sudo apt-get install -y curl gnupg2 software-properties-common
        curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /usr/share/keyrings/llvm-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/focal/ llvm-toolchain-focal-${{ matrix.llvm-version }} main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get update
        sudo apt-get install -y clang-${{ matrix.llvm-version }} llvm-${{ matrix.llvm-version }}

    - name: Verify Clang/LLVM Installation
      run: |
        clang-${{ matrix.llvm-version }} --version
        llvm-config-${{ matrix.llvm-version }} --version

    - name: Set up JDK 11 (Temurin)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          git g++ cmake bison flex libboost-all-dev python3 \
          perl minisat curl wget locales

    - name: Generate test files (LLVM IR)
      run: |
        cd benchmarks/llvm && make gensym
        cd ../demo-benchmarks && make gensym
        cd ../external-lib && make gensym
        cd ../oopsla20 && make generate_sse
        cd ../test-comp/array-examples && make gensym
        cd ../../test-comp/array-programs && make gensym
        cd ../../klee-posix-fs && make

    - name: Install Z3
      run: |
        cd third-party
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.14/z3-4.8.14-x64-glibc-2.31.zip
        unzip z3-4.8.14-x64-glibc-2.31.zip
        cd z3-4.8.14-x64-glibc-2.31
        sudo cp include/* /usr/include/
        sudo cp bin/libz3.so /usr/lib/x86_64-linux-gnu/
        sudo ldconfig

    - name: Install STP
      run: |
        cd third-party/stp
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Install wasmfx-tools
      run: |
        cd third-party/wasmfx-tools
        cargo build --release

    - name: Generate models
      run: sbt 'runMain gensym.GenerateExternal'

    - name: Run tests
      run: |
        sbt 'testOnly gensym.TestImpCPSGS'
        sbt 'testOnly gensym.TestImpCPSGS_Z3'
        sbt 'testOnly gensym.TestLibrary'
        sbt 'testOnly gensym.wasm.TestEval'
        sbt 'testOnly gensym.wasm.TestScriptRun'

    - name: Cleanup
      run: |
        sudo rm -rf ~/.sbt ~/.ivy2 ~/.cache
